{
 "title": "Windows Server Monitor",
 "description": "Basic overview of windows host metrics, based on WMI Exporter (v0.7.0)",
 "tags": [
  "windows_exporter",
  "windows",
  "ops",
  "prometheus",
  "monitor"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(windows_os_time, job)"
   },
   {
    "name": "host",
    "label": "Windows Server",
    "query": "label_values(windows_os_time{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime | $host",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "repeat": "host",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_os_time {instance=\"10.51.188.101:9182\"} - windows_system_system_up_time {instance=\"10.51.188.101:9182\"}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "repeat": "host",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_cs_logical_processors{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(irate(windows_cpu_time_total{instance=~\"$host\",mode=\"idle\"}[5m])) > 0"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(windows_os_physical_memory_free_bytes{instance=~\"$host\"} / windows_cs_physical_memory_bytes{instance=~\"$host\"}) > 0"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(windows_logical_disk_free_bytes{instance=~\"$host\",volume=~\"^[A-Z]:.*$\"}) / sum(windows_logical_disk_size_bytes{instance=~\"$host\",volume=~\"^[A-Z]:.*$\"})) > 0"
    }
   ]
  },
  {
   "title": "Net IN (24h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "Data transfer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate(windows_logical_disk_write_bytes_total{instance=~\"$host\",volume !~\"HarddiskVolume.+\"}[1m])) without (volume) + sum (irate(windows_logical_disk_read_bytes_total{instance=~\"$host\",volume !~\"HarddiskVolume.+\"}[1m])) without (volume)"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "expr": "sort_desc(windows_logical_disk_free_bytes{instance=~\"$host\",volume=~\"(^[A-Z]:$)\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Net OUT (24h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 2 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 2 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (irate(windows_logical_disk_split_ios_total{instance=~\"$host\",volume !~\"HarddiskVolume.+\"}[1m])) without (volume)"
    }
   ]
  },
  {
   "title": "CPU Load | $host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "repeat": "host",
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(windows_cpu_time_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Exceptions | $host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_system_exception_dispatches_total{instance=~\"$host\"}[5m])",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "System Threads | $host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_system_threads{instance=~\"$host\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Memory | $host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "windows_os_virtual_memory_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Virtual"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Physical"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Traffic | $host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) > 0",
     "legendFormat": "Received"
    },
    {
     "expr": "- irate(windows_net_bytes_sent_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) < 0",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network discarded/error | $host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 9 },
   "repeat": "host",
   "yaxes": [
    { "format": "pps", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_packets_outbound_discarded{instance=~\"$host\",nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_outbound_errors{instance=~\"$host\"}[5m])",
     "legendFormat": "Sent ({{nic}})"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded{instance=~\"$host\", nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_received_errors{instance=~\"$host\"}[5m])",
     "legendFormat": "Received ({{nic}})"
    }
   ]
  },
  {
   "title": "Disk (Free) | $host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Service",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "windows_service_state{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk Activity | $host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 14 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- irate(windows_logical_disk_write_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
     "legendFormat": "Read {{volume}}"
    }
   ]
  },
  {
   "title": "Disk IO | $host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- irate(windows_logical_disk_write_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_read_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
     "legendFormat": "Read {{volume}}"
    }
   ]
  }
 ]
}